### ISSUE TITLE
Issue with pre and code tags

### ISSUE THREAD

**Issue by funcoding** [j0k3r/php-readability#19]
When using the url: https://www.digitalocean.com/community/tutorials/how-to-secure-your-redis-installation-on-ubuntu-14-04 , I am getting the following error in the result
![error](https://cloud.githubusercontent.com/assets/2198105/20834427/58e0e84a-b8bb-11e6-9b59-e3c237c45ec7.png)

I think the issue with closing the `pre` tag. It is opening but it is closing after only nesting everything. Also the `code` tag is switched with pre tag

**Comment by j0k3r** [comment]
It looks like I don't have any problem.
Could show me the bad code you described?

----

![image](https://cloud.githubusercontent.com/assets/62333/22853196/f08b7d7e-f04f-11e6-830d-3fa4b7cd3768.png)

----

Also, [by default](https://github.com/j0k3r/php-readability/blob/8b1c3f147d7287f1cbea5097640c142fc2ad29fe/src/Readability.php#L148-L149), the `<code>` node are replaced by `<pre>`.

You can disabled that using `$readability->addFlag(Readability::FLAG_DISABLE_POSTFILTER);`.

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
