### ISSUE TITLE
How to get image

### ISSUE THREAD

**Issue by kapil019** [j0k3r/php-readability#2]
How to get image for redabilty.

**Comment by j0k3r** [comment]
What do you mean?

**Comment by kapil019** [comment]
Can i scrapp images from remote url. 
Like i want to scrapp a product from http://www.jabong.com/raymond-Yellow-Regular-Formal-Shirt-710004.html?pos=16
And i need to save this image to local system.

Is this possible?

**Comment by j0k3r** [comment]
Since I don't use this kind of feature I removed it from the original fork.

You can find it here: https://github.com/Dither/full-text-rss/tree/master/libraries/readability and feel free to submit a PR to re-add it.
