### ISSUE TITLE
Missing namespace for HTML5_Parser

### ISSUE THREAD

**Issue by nicosomb** [j0k3r/php-readability#20]
In `src/Readability.php`, you use `HTML5_Parser` but this class isn't found. 

You can find it here: https://github.com/silverstripe/silverstripe-html5/tree/master/thirdparty/html5lib/HTML5
Or in wallabag 1.x zip.

**Comment by j0k3r** [comment]
Are you using it?
Also https://github.com/Masterminds/html5-php seems to be more accurate.

**Comment by nicosomb** [comment]
I had an error yesterday during my massive imports. I can't retrieve the concerned URL (maybe this one http://fm4v2.orf.at/stories/1774409%5c//main.html but not sure).

**Comment by nicosomb** [comment]
I confirm that it's this URL.

**Comment by j0k3r** [comment]
Sadly, I got a 404 with that url now 😞
