### ISSUE TITLE
Preserve newlines?

### ISSUE THREAD

**Issue by Anahkiasen** [j0k3r/php-readability#28]
I'm trying to convert articles to readable blobs of text, however I would like for `<br>` and `<p>` tags to be converted as newlines, currently the package returns one big inline string of text. Is this possible at the moment?

**Comment by j0k3r** [comment]
There is a `pre_filters` which converts all newlines to paragraph: https://github.com/j0k3r/php-readability/blob/master/src/Readability.php#L131

Maybe you can add a `post_filters` to convert all paragraph to newline **and** paragraph

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
