### ISSUE TITLE
Error: A non well formed numeric value encountered

### ISSUE THREAD

**Issue by nicofrand** [j0k3r/php-readability#49]
Hi!

I am trying to run a dev instance of wallabag but I can't import any article, due to an error in Readability (wallabag error: `[2019-05-08 19:11:22] app.ERROR: Error while saving an entry {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Notice: A non well formed numeric value encountered at /home/nicofrand/www/wallabag/vendor/j0k3r/php-readability/src/Readability.php:1118)","entry":"[object] (Wallabag\\CoreBundle\\Entity\\Entry: {})"} []
`).

Example of a link: https://blog.eleven-labs.com/fr/po-vs-pm-like-batman-vs-superman/

The error in Readability:

```PHP
Symfony\Component\Debug\Exception\ContextErrorException: Notice: A non well formed numeric value encountered in /home/nicofrand/www/wallabag/vendor/j0k3r/php-readability/src/Readability.php on line 1118
```

Line 1118 https://github.com/j0k3r/php-readability/blob/master/src/Readability.php#L1118 the values are:

`$grandParentNode->getAttributeNode('readability')->value` = `'4,0909090909091'`.
`$contentScore` = `1,3636363636364`.

That might come from my config since I have no issue with a prod version of wallabag on my server but I can't find why this happens… Would you have an idea?

Thanks in advance!

**Comment by j0k3r** [comment]
Could you share which version of PHP you are using? Also, which version of wallabag you are trying to install?

**Comment by nicofrand** [comment]
Of course.

I am using PHP 7.2.1 (I'll confirm later the exact version).

I did install wallabag, the dev version (through `make dev`), the "only" thing not working is the fetch of an article: it is created but without any content. I saw the error in the dev.log file.

**Comment by nicofrand** [comment]
To be exact:
```
PHP 7.2.17-0ubuntu0.19.04.1 (cli) (built: Apr 18 2019 18:01:25) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.17-0ubuntu0.19.04.1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.1, Copyright (c) 2002-2018, by Derick Rethan
```

**Comment by j0k3r** [comment]
I can not reproduce the bug using the dev version of wallabag.
Can you check your composer.lock for `"name": "j0k3r/php-readability",` and tell me which version is installed?
Same for `"name": "j0k3r/graby-site-config",`.

**Comment by nicofrand** [comment]
```

            "name": "j0k3r/graby",
            "version": "1.19.1",
            "source": {
                "type": "git",
                "url": "https://github.com/j0k3r/graby.git",
                "reference": "6c1506f19d1bb876fb26bfc11e3e11a993eb7fe8"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/j0k3r/graby/zipball/6c1506f19d1bb876fb26bfc11e3e11a993eb7fe8",
                "reference": "6c1506f19d1bb876fb26bfc11e3e11a993eb7fe8",
                "shasum": ""
            },
            "require": {
                "ext-curl": "*",
                "fossar/htmlawed": "^1.2.4",
                "guzzlehttp/guzzle": "^5.2.0",
                "j0k3r/graby-site-config": "^1.0",
                "j0k3r/php-readability": "^1.0",
                "j0k3r/safecurl": "~2.0",
```

**Comment by j0k3r** [comment]
Do you have the php tidy extension installed?

**Comment by nicofrand** [comment]
Yes I do.

**Comment by nicofrand** [comment]
I reproduce with this:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

ini_set('display_errors', 'On');
error_reporting(E_ALL);

use Readability\Readability;

$url = 'https://blog.eleven-labs.com/fr/po-vs-pm-like-batman-vs-superman/';


// you can use whatever you want to retrieve the html content (Guzzle, Buzz, cURL ...)
$html = file_get_contents($url);

$readability = new Readability($html, $url);
// or without Tidy
// $readability = new Readability($html, $url, 'libxml', false);
$result = $readability->init();

if ($result) {
    // display the title of the page
    echo $readability->getTitle()->textContent;
    // display the *readability* content
    echo $readability->getContent()->textContent;
} else {
    echo 'Looks like we couldn\'t find the content. :(';
}
```

Do you?

**Comment by nicofrand** [comment]
This produces `Notice` only (but wallabag stops the fetch due to those errors being caught on an upper level).

![image](https://user-images.githubusercontent.com/3419050/57555475-a4cfe780-7374-11e9-9752-b783f141c3d8.png)

**Comment by nicofrand** [comment]
Argh no, it's ok with 1.2 sorry…

**Comment by nicofrand** [comment]
I can't actually reproduce with readability (or graby) alone, only in wallabag… I am closing for now
