### ISSUE TITLE
Entity 'nbsp' may be not defined in dtd,but in readability this entity is been used.

### ISSUE THREAD

**Issue by MikeIvantsov** [j0k3r/php-readability#5]
DOMDocumentFragment::appendXML(): Entity: line 3: parser error : Entity 'nbsp' not defined;

The original html-document does not contain "nbsp", but the exception was generated.

Example, DTD:
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

**Comment by j0k3r** [comment]
Could you give me the content or url your were using to reproduce the bug?

**Comment by MikeIvantsov** [comment]
http://iosgames.ru/?p=22030

**Comment by j0k3r** [comment]
Thanks I'll take a closer look.

**Comment by MikeIvantsov** [comment]
I think the problem at the code between 530 and 560 lines : $iframe->item(0)->nodeValue = '&nbsp;'

**Comment by j0k3r** [comment]
Could you give me a snippet how to reproduce the bug?
I've tried with that:

```php
<?php

require 'vendor/autoload.php';

$url = 'http://iosgames.ru/?p=22030';
$data = file_get_contents($url);

$readability = new \Readability\Readability($data, $url);
$result = $readability->init();

var_dump($result, $readability); die();
```

And I didn't get any errors.
Which version of PHP are you using? Did you have the tidy extension installed?

**Comment by MikeIvantsov** [comment]
PHP 5.3.10-1ubuntu3.19
Tidy support => enabled
libTidy Release => 25 March 2009
Extension Version => 2.0

Try that:
```PHP
function error2Exception($code, $string, $file, $line, $context)
{
	throw new Exception($string, $code);
}
error_reporting(E_ALL | E_STRICT);
ini_set('display_errors', true);
set_error_handler('error2Exception', E_ALL | E_STRICT);

require 'vendor/autoload.php';

$url = 'http://iosgames.ru/?p=22030';
$data = file_get_contents($url);

$readability = new \Readability\Readability($data, $url);
$result = $readability->init();

var_dump($result, $readability); die();
```
Exception from my script:

PHP Fatal error:  Uncaught exception 'Exception' with message 'DOMDocumentFragment::appendXML(): Entity: line 3: parser error : Entity 'nbsp' not defined' in test.php:14
Stack trace:
#0 [internal function]: error2Exception(2, 'DOMDocumentFrag...', '/home/www/libs/...', 57, Array)
#1 /home/www/libs/php-readability/src/JSLikeHTMLElement.php(57): DOMDocumentFragment->appendXML('<div class="ent...')
#2 /home/www/libs/php-readability/src/Readability.php(559): Readability\JSLikeHTMLElement->__set('innerHTML', '<div class="ent...')
#3 /home/www/libs/php-readability/src/Readability.php(911): Readability\Readability->prepArticle(Object(Readability\JSLikeHTMLElement))
#4 /home/www/libs/php-readability/src/Readability.php(291): Readability\Readability->grabArticle()
#5 test.php(27): Readability\Readability->init()
#6 {main}
  thrown in test.php on line 14
