### ISSUE TITLE
Question on Tidy

### ISSUE THREAD

**Issue by harikt** [j0k3r/php-readability#6]
Hi, 

I am here after trying to install https://github.com/wallabag/wallabag/tree/v2 . Noticed I have not installed the php extension tidy. 

Do you think it is still necessary to install tidy or can we move to use something like https://packagist.org/packages/ezyang/htmlpurifier .

I have not used tidy before to say the good things about it. 

Interested to hear what you think.

Thank you

**Comment by j0k3r** [comment]
As you may noticed, this version is a fork of an [existing library](https://bitbucket.org/fivefilters/php-readability/overview) which is an improvement of a [previous library](http://www.keyvan.net/2010/08/php-readability/).

From the very beginning, both library were using Tidy. In fact, I never asked myself if I should remove Tidy with something else.
Tidy still evolve, in a good way. You can see the project [here](https://github.com/htacg/tidy-html5).

The project here has already filters things to be removed, it also use a fine tuning Tidy configuration to cleanup the HTML and finally some regexps. Maybe HtmlPurifier can done a better job here? I don't know.

I think it will require lots of work to remove Tidy in favor to HtmlPurifier. But feel free to provide a PR, I'll be happy to review it !

**Comment by harikt** [comment]
Thank you for the explanation.

**Comment by j0k3r** [comment]
Just to let you know that the lib will work **without** Tidy soon https://github.com/j0k3r/php-readability/pull/10
