### ISSUE TITLE
Problem with article extraction

### ISSUE THREAD

**Issue by Lucas-C** [j0k3r/php-readability#82]
Hi!

I use [wallabag](https://github.com/wallabag/wallabag), that uses [j0k3r/php-readability 1.2.10](https://github.com/wallabag/wallabag/blob/master/composer.lock#L4695).

On some websites, I found out that some Javascript code snippets are "polluting" the text context extracted.

This happens for example on this page: https://lesprosdelapetiteenfance.fr/eveil-activites/ateliers-pedagogiques-et-fiches-activites/maquillage-et-pate-modeler-5-recettes-bio

Some JavaScript inline code seems to generate `<div>` elements (for example on line 1376),
and PHP Readability ends up extracting some of this JS code:
```javascript
                   $('.sib_list_row').append('<div class="message_area" style="background-color: #f2dede;border:1px solid #ebccd1; color: #a94442;margin-top: 5px;"><button type="button" class="close">x</button>' + emptyError + '</div>');
```

The resulting article looks like this:
> ### Inscrivez-vous à la newsletter
> '); } }else { var input = theForm.find('input[name="' + required[i] + '"]'); var inputType = input.attr('type'); if (inputType == 'text' || inputType == 'number') { if (input.val() == "" || input.val() == emptyError) { input.closest('.row').addClass("needsfilled"); input.closest('.row').append('
> ' + emptyError + '

Could you please help regarding this? How can this be fixed?

**Comment by j0k3r** [comment]
Well, it might not be a problem from readability.
In fact, it can be handle using site config and some rules to remove extra stuff.

I managed to get a clean content:
![Capture d’écran 2023-08-24 à 14 34 51](https://github.com/j0k3r/php-readability/assets/62333/263daacd-bc8c-4fd5-9c68-196a939ec1d1)

If it's look ok to you, I'll push the siteconfig update.

**Comment by Lucas-C** [comment]
Wow, amazing, this looks great!

Well done it getting such clean content!
Yes, it totally looks OK to me 😊

Thank you!

**Comment by Lucas-C** [comment]
Top, merci !
