### ISSUE TITLE
how can i get Excerpt, image and Author?

### ISSUE THREAD

**Issue by nbao** [j0k3r/php-readability#83]
Hello,
How can i get Excerpt, image and Author?
with fivefilters/php-readability i can get all information like this

              "title" => $readability->getTitle(),
              "content" => $readability->getContent(),
              "excerpt" => $readability->getExcerpt(),
              "lead_image_url" => $readability->getImage(),
              "author" => $readability->getAuthor(),

**Comment by j0k3r** [comment]
You can only retrieve title & content:

```php
$title = $readability->getTitle();
$content = $readability->getContent();
```

If you want to retrieve more information, I suggest you to use https://github.com/j0k3r/graby instead.

**Comment by nbao** [comment]
Bonjour 
J'ai une erreur lors de composer install avec Graby, 

    - j0k3r/graby[1.0.0, ..., 1.20.1] require guzzlehttp/guzzle ^5.2.0 -> found guzzlehttp/guzzle[5.2.0, ..., 5.3.4] but the package is fixed to 7.7.1 (lock file version) by a partial update and that version does not match. Make sur
e you list it as an argument for the update command.
    - j0k3r/graby[2.0.0, ..., 2.4.4] require ext-tidy * -> it is missing from your system. Install or enable PHP's tidy extension.

Je souhaite intégrer Graby à Drupal en option
voici module 
[URL parser](https://www.drupal.org/project/postlight_parser)
Je pense que la plupart des serveurs (serveurs mutualisé) n'ont pas php-tidy, que vous pouvez enlever php-ext-tidy?

**Comment by j0k3r** [comment]
Non je ne peux pas l'enlever, tidy est une composante importante dans Graby.
Vous devriez forcer Graby 2.0 plutôt que Graby 1.0. La version 2 n'est plus directement liée à Guzzle.

**Comment by nbao** [comment]
Votre travail est incroyable, le content est plus clair plus précis que readability. Est ce qu'il y a option pour garder les tag img dans content?
je ne savais tout simplement pas que vous pouviez obtenir le lien de youtube, dailymotion, tiktok... ? Actuellement j'utilise la bibliothèque [embera ](https://github.com/mpratt/Embera) pour obtenir les information. Si elle peut être intégrée à votre module, ce serait mieux.
J'ai testé Graby avec beaucoup de liens. Il y a 10%, il est retourné faux (marché avec readability)
