### ISSUE TITLE
problem install (tidy dependencies)

### ISSUE THREAD

**Issue by metasystem** [j0k3r/php-readability#9]
Hi,
I run archlinux on atom d525 with PHP 5.6.15, extra/php-tidy 5.6.15-2 installed and detected in active php version modules, activated in php.ini. Other modules works fine on others composer install, but not tidy...
I want to install wallabag-2.x and it would be great I can install php-readability...
Thx for all

**Comment by j0k3r** [comment]
What kind of error do you get? Is it when launching `composer install` ?

**Comment by metasystem** [comment]
hi,
Thx for this quick answer.
Yes, error is in composer install:
http://sprunge.us/LcNT
Cordially

**Comment by j0k3r** [comment]
Does tidy is enable for PHP CLI ?
Could you run `php -i | grep tidy` ?

**Comment by metasystem** [comment]
yes, it does:
http://sprunge.us/MajZ

**Comment by j0k3r** [comment]
Travis doesn't support Arch Linux so it's hard for me to run some tests.
Can you show me result for these commands:
- `php -r "var_dump(extension_loaded('tidy'));"`
- `php -r "var_dump(function_exists('tidy_parse_string'));"`

**Comment by metasystem** [comment]
> [root@localhost meta-system]# php -r "var_dump(extension_loaded('tidy'));"
> bool(true)

> [root@localhost meta-system]# php -r "var_dump(function_exists('tidy_parse_string'));"
> bool(true)

No problem about don't have support actually, I understand... But is it very strange to have a correct php detect about tidy and a simple module don't detect him... I hope you have potentially a solution...
If you need it, I can give you ssh access exceptionally to test it directly...
Thx for your help...

**Comment by j0k3r** [comment]
Wow, stunning results. I didn't expect that.
This is how Composer check availability of an extension (here only the error message):

```php
$error = extension_loaded($ext) ? 'has the wrong version ('.(phpversion($ext) ?: '0').') installed' : 'is missing from your system';
```

So it should work on your system ...

In fact, the first version of this lib had ability to work without tidy installed:

```php
public function __construct($html, $url = null, $parser = 'libxml', $use_tidy = true)
```

So, it won't be hard to disable this verification in Composer. Anyway, I'll have to update the test suite to be sure everything work great without tidy.

**Comment by metasystem** [comment]
Is it possible the problem only exist in tidy detect and installation work with correct php tidy request after?
That you say, it would be interesting that I contact composer devs to tell them if there is possibly a bug?

**Comment by j0k3r** [comment]
It could be interesting to dig a little deeper into that point for Composer yep!

**Comment by metasystem** [comment]
just going on a similar issue on composer github and try 
> composer show -p
with results http://sprunge.us/VHWe
Apparently it seems that tidy is correctly installed, but not detected on composer... I have to read issue and see if I can solve it...

**Comment by j0k3r** [comment]
Interesting :+1:

**Comment by j0k3r** [comment]
Hum also, do you have an up to date Composer ? Try to run `composer selfupdate` and re-try the `composer install`.

**Comment by metasystem** [comment]
already up to date...
I have changed PKGBUILD in community archlinux repo to have git up to date... :P
I have many problems on archlinux wich many others programs (cozycloud for example, virtualbox-headless, etc...) So, I'm debootstraping debian jessie...
I never had an already buggy distro before, and I'm using funtoo... So I prefere coming back on debian on my atom server... I will try if problem persist on this new install...
Keeping archlinux install on subvolume if needed for test

**Comment by metasystem** [comment]
after reinstall on debian, problem doesn't exist, so it seems to be composer on arch that have module detecting problem...
closing issue

**Comment by j0k3r** [comment]
All right, thanks for letting me know.
I'll still work on the non-tidy deps version.

**Comment by metasystem** [comment]
it would be great I think, but you have not solve archlinux problem... So, don't worry if someone have the same problem, I think he have to change to debian (this is not bad in fact... :P )
